### ISSUE TITLE
Can Not run

### ISSUE THREAD

**Issue by payneje** [hyperlink/plex-tv-cleanup#1]
I have followed the directions but for some reason it is not finding the config..even though I am putting it where it tells me

Jims-iMac:~ root# plex-tv-cleanup --dry-run
✖ Please create /var/root/.plex-tv-cleanup-config.json with your configuration. See https://github.com/hyperlink/plex-tv-cleanup/blob/master/README.md#installation
Jims-iMac:~ root# echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Jims-iMac:~ root# ls -altrh
total 32
-r--r--r--   1 root  wheel    10B Aug 24  2015 .forward
-rw-r--r--   1 root  wheel     3B Jan  6  2016 .CFUserTextEncoding
drwx------  12 root  wheel   408B Jan  8  2016 Library
drwxr-xr-x   3 root  wheel   102B Jan 10  2016 .oracle_jre_usage
drwx------   3 root  wheel   102B Jan 10  2016 .ssh
drwxr-xr-x  25 root  wheel   850B Jul 26 16:38 ..
drwxr-xr-x  94 root  wheel   3.1K Sep  3 09:05 .npm
-rwxr-xr-x   1 root  wheel   373B Sep  3 09:16 .plex-tv-cleanup-config.json
-rw-------   1 root  wheel   2.0K Sep  3 09:47 .sh_history
-rw-------   1 root  wheel   3.5K Sep  3 09:57 .viminfo
drwxr-x---  11 root  wheel   374B Sep  3 09:57 .
Jims-iMac:~ root# pwd
/var/root

**Comment by hyperlink** [comment]
Maybe this is a permission issue? Are you sure the process could read this file?
