### ISSUE TITLE
After a recent plex update, getting an error

### ISSUE THREAD

**Issue by ajdexter** [hyperlink/plex-tv-cleanup#2]
Plex Server Version 1.3.3.3148
NPM 2.15.8
Node v4.4.7

After a recent Plex update I'm getting the following error, which is preventing files from being process/removed.

-------
Delete failed [TypeError: Cannot read property 'filter' of undefined]

✔ Total (would be) deleted: NaN episodes
✔ Space (would be) recovered: 0.00 PB
-----

Any help sorting is much appreciated.

**Comment by hyperlink** [comment]
Yeah, I'm getting this error too. I'll take a look at it tonight.

**Comment by ajdexter** [comment]
Thanks for checking into it @hyperlink. It seems possible that the JSON responses could be the culprit here... oy

**Comment by hyperlink** [comment]
That's exactly what it is @ajdexter I verified it last night. Looking forward to a fix in the `node-plex-api` dependency.

**Comment by ajdexter** [comment]
Cool. Thanks for following up, I'll keep an eye on the node-plex-api side as well. Cheers

**Comment by hyperlink** [comment]
@ajdexter I fixed the issue in my fork of `node-plex-api`. So from the perspective of this module it should be fixed now. Please update and let me know if it's working for you.

**Comment by ajdexter** [comment]
@hyperlink Works great and 34GB cleared. Thank you so much for the updates and help.
